services:
  db:
    image: mysql:8.4.7
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Password9527 # account: root
    ports:
      - 3306:3306
  
  adminer: # 数据库管理工具
    image: adminer
    restart: always
    ports:
      - 8080:8080
